// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

Future<List<PipewireApp>> pipewireApplications() =>
    RustLib.instance.api.crateTranscribeTranscribePipewireApplications();

Future<void> startTranscribing(
        {required String modelPath,
        required int bufferSeconds,
        String? target,
        String? outputDir,
        String? language,
        required FutureOr<void> Function(TranscriptionSegment)
            segmentCallback}) =>
    RustLib.instance.api.crateTranscribeTranscribeStartTranscribing(
        modelPath: modelPath,
        bufferSeconds: bufferSeconds,
        target: target,
        outputDir: outputDir,
        language: language,
        segmentCallback: segmentCallback);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TranscriptionSegment>>
abstract class TranscriptionSegment implements RustOpaqueInterface {
  double get endTimestamp;

  double get startTimestamp;

  String get text;

  set endTimestamp(double endTimestamp);

  set startTimestamp(double startTimestamp);

  set text(String text);
}

class PipewireApp {
  final int id;
  final String name;
  final String mediaClass;

  const PipewireApp({
    required this.id,
    required this.name,
    required this.mediaClass,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ mediaClass.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PipewireApp &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          mediaClass == other.mediaClass;
}
