// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<void> startTranscribing(
        {required String modelPath,
        required int bufferSeconds,
        String? target,
        String? outputDir,
        String? language,
        required FutureOr<void> Function(WhisperSegment) segmentCallback}) =>
    RustLib.instance.api.crateTranscribeTranscribeStartTranscribing(
        modelPath: modelPath,
        bufferSeconds: bufferSeconds,
        target: target,
        outputDir: outputDir,
        language: language,
        segmentCallback: segmentCallback);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TranscriptionSegment>>
abstract class TranscriptionSegment implements RustOpaqueInterface {
  double get endTimestamp;

  double get startTimestamp;

  String get text;

  set endTimestamp(double endTimestamp);

  set startTimestamp(double startTimestamp);

  set text(String text);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<WhisperSegment>>
abstract class WhisperSegment implements RustOpaqueInterface {}
