// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<void> startTranscribing(
        {required String modelPath,
        required int bufferSeconds,
        String? target,
        String? outputDir,
        String? language,
        required FutureOr<void> Function(TranscriptionSegment)
            segmentCallback}) =>
    RustLib.instance.api.crateTranscribeTranscribeStartTranscribing(
        modelPath: modelPath,
        bufferSeconds: bufferSeconds,
        target: target,
        outputDir: outputDir,
        language: language,
        segmentCallback: segmentCallback);

class TranscriptionSegment {
  final String text;
  final double startTimestamp;
  final double endTimestamp;

  const TranscriptionSegment({
    required this.text,
    required this.startTimestamp,
    required this.endTimestamp,
  });

  @override
  int get hashCode =>
      text.hashCode ^ startTimestamp.hashCode ^ endTimestamp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TranscriptionSegment &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          startTimestamp == other.startTimestamp &&
          endTimestamp == other.endTimestamp;
}
