[package]
name = "pipescribe"
version = "0.1.1"
edition = "2024"
license = "GPL-3.0-or-later"
description = "A tool for real-time transcription of audio streams using Whisper and PipeWire."
repository = "https://github.com/mz2/pipescribe"

[features]
default = []
cuda = ["whisper-rs/cuda"]

# Define the library target
[lib]
name = "pipescribe"
path = "src/lib.rs"

# Define the binary targets
[[bin]]
name = "pipescribe"
path = "src/main.rs"


[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.37", features = ["derive"] }
crossbeam-channel = "0.5.15"
env_logger = "0.11.8"
hound = "3.5.1"
libspa-sys = "0.8.0"
log = "0.4.27"
pipewire = "0.8.0"
pipewire-sys = "0.8.0"
regex = "1.11.1"
spa = "0.5.1"
tempfile = "3.19.1"
tokio = { version="1.44.2", features=["rt-multi-thread", "sync", "macros", "time"] }
whisper-rs = { git = "https://git@github.com/mz2/whisper-rs.git", branch = "fpic-fix", features = ["log_backend"] }
