[package]
name = "rust_lib_pipescribe"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
anyhow = "1.0.98"
env_logger = "0.11.8"
flutter_rust_bridge = "=2.9.0"
log = "0.4.27"
pipescribe = { path = "../../", features=["cuda"] }
tokio = { version="1.44.2", features=["rt-multi-thread", "sync", "macros"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
