name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev libssl-dev pkg-config libpipewire-0.3-dev build-essential

      - name: Install CUDA
        run: |
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-keyring_1.1-1_all.deb
          sudo dpkg -i cuda-keyring_1.1-1_all.deb
          sudo apt-get update
          sudo apt-get -y install cuda-toolkit-12-3
          echo "CUDA_HOME=/usr/local/cuda" >> $GITHUB_ENV
          echo "/usr/local/cuda/bin" >> $GITHUB_PATH
          # Verify CUDA installation
          nvcc --version

      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --features cuda
        env:
          RUSTFLAGS: "-C link-arg=-Wl,-rpath,/usr/local/cuda/lib64"

      - name: Download Whisper model
        run: |
            mkdir -p models
            if [ ! -f "models/ggml-tiny.en.bin" ]; then
              ./bin/download-ggml-models.sh tiny.en
              cp ./ggml-tiny.en.bin models/
            fi
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --features cuda
        env:
          RUSTFLAGS: "-C link-arg=-Wl,-rpath,/usr/local/cuda/lib64"

      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --features cuda -- -D warnings
